FROM golang:1.20.4-bullseye@sha256:8251849ec0e15a94170dec220e2da16b0d066e82dfbb462ac8402818de8050cc as builder

COPY ./server /go/src/github.com/envoyproxy/envoy/example/load-reporting-service/server
COPY *.go /go/src/github.com/envoyproxy/envoy/example/load-reporting-service/
COPY go.sum /go/src/github.com/envoyproxy/envoy/example/load-reporting-service
COPY go.mod /go/src/github.com/envoyproxy/envoy/example/load-reporting-service

WORKDIR /go/src/github.com/envoyproxy/envoy/example/load-reporting-service
RUN go mod download \
    && go install /go/src/github.com/envoyproxy/envoy/example/load-reporting-service

FROM debian:bullseye-slim

COPY --from=builder /go/bin/load-reporting-service /usr/local/bin/load-reporting-service

CMD ["load-reporting-service"]
